version: "3.9"

services:
    php:
        build:
            context: ./docker/php
        container_name: symfony-php
        working_dir: /var/www/symfony
        volumes:
            - ./:/var/www/symfony
        depends_on:
            - mysql
            - redis
        networks:
            - symfony

    nginx:
        image: nginx:1.25
        container_name: symfony-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/symfony
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - symfony

    mysql:
        image: mysql:8.0
        container_name: symfony-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - symfony

    redis:
        image: redis:7.2
        container_name: symfony-redis
        ports:
            - "6379:6379"
        networks:
            - symfony

volumes:
    db_data:

networks:
    symfony:
